touch README.md
touch source/chapter1/01_Objectives.md
touch source/chapter1/02_GettingStarted.md
touch source/chapter1/03_WhatIsComputerScience.md
touch source/chapter1/04_WhatIsProgramming.md
touch source/chapter1/05_WhyStudyDataStructuresandAbstractDataTypes.md
touch source/chapter1/06_WhyStudyAlgorithms.md
touch source/chapter1/07_ReviewofBasicPython.md
touch source/chapter1/08_GettingStartedwithData.md
touch source/chapter1/09_InputandOutput.md
touch source/chapter1/10_ControlStructures.md
touch source/chapter1/11_ExceptionHandling.md
touch source/chapter1/12_DefiningFunctions.md
touch source/chapter1/13_ObjectOrientedProgramminginPythonDefiningClasses.md
touch source/chapter1/14_Summary.md
touch source/chapter1/15_KeyTerms.md
touch source/chapter1/16_DiscussionQuestions.md
touch source/chapter1/17_ProgrammingExercises.md
touch source/chapter2/01_Objectives.md
touch source/chapter2/02_WhatIsAlgorithmAnalysis.md
touch source/chapter2/03_BigONotation.md
touch source/chapter2/04_AnAnagramDetectionExample.md
touch source/chapter2/05_PerformanceofPythonDataStructures.md
touch source/chapter2/06_Lists.md
touch source/chapter2/07_Dictionaries.md
touch source/chapter2/08_Summary.md
touch source/chapter2/09_KeyTerms.md
touch source/chapter2/10_DiscussionQuestions.md
touch source/chapter2/11_ProgrammingExercises.md
touch source/chapter3/01_Objectives.md
touch source/chapter3/02_WhatAreLinearStructures.md
touch source/chapter3/03_WhatisaStack.md
touch source/chapter3/04_TheStackAbstractDataType.md
touch source/chapter3/05_ImplementingaStackinPython.md
touch source/chapter3/06_SimpleBalancedParentheses.md
touch source/chapter3/07_BalancedSymbols
touch source/chapter3/08_ConvertingDecimalNumberstoBinaryNumbers.md
touch source/chapter3/09_InfixPrefixandPostfixExpressions.md
touch source/chapter3/10_WhatIsaQueue.md
touch source/chapter3/11_TheQueueAbstractDataType.md
touch source/chapter3/12_ImplementingaQueueinPython.md
touch source/chapter3/13_SimulationHotPotato.md
touch source/chapter3/14_SimulationPrintingTasks.md
touch source/chapter3/15_WhatIsaDeque.md
touch source/chapter3/16_TheDequeAbstractDataType.md
touch source/chapter3/17_ImplementingaDequeinPython.md
touch source/chapter3/18_PalindromeChecker.md
touch source/chapter3/19_Lists.md
touch source/chapter3/20_TheUnorderedListAbstractDataType.md
touch source/chapter3/21_ImplementinganUnorderedListLinkedLists.md
touch source/chapter3/22_TheOrderedListAbstractDataType.md
touch source/chapter3/23_ImplementinganOrderedList.md
touch source/chapter3/24_Summary.md
touch source/chapter3/25_KeyTerms.md
touch source/chapter3/26_DiscussionQuestions.md
touch source/chapter3/27_ProgrammingExercises.md
touch source/chapter4/01_Objectives.md
touch source/chapter4/02_WhatIsRecursion.md
touch source/chapter4/03_pythondsCalculatingtheSumofaListofNumbers.md
touch source/chapter4/04_TheThreeLawsofRecursion.md
touch source/chapter4/05_pythondsConvertinganIntegertoaStringinAnyBase.md
touch source/chapter4/06_StackFramesImplementingRecursion.md
touch source/chapter4/07_pythondsintro-VisualizingRecursion.md
touch source/chapter4/08_pythondsSierpinskiTriangle.md
touch source/chapter4/09_ComplexRecursiveProblems.md
touch source/chapter4/10_TowerofHanoi.md
touch source/chapter4/11_ExploringaMaze.md
touch source/chapter4/12_DynamicProgramming.md
touch source/chapter4/13_Summary.md
touch source/chapter4/14_KeyTerms.md
touch source/chapter4/15_DiscussionQuestions.md
touch source/chapter4/16_Glossary.md
touch source/chapter4/17_pythondsProgrammingExercises.md
touch source/chapter5/01_Objectives.md
touch source/chapter5/02_searching.md
touch source/chapter5/03_TheSequentialSearch.md
touch source/chapter5/04_TheBinarySearch.md
touch source/chapter5/05_Hashing.md
touch source/chapter5/06_sorting.md
touch source/chapter5/07_TheBubbleSort.md
touch source/chapter5/08_TheSelectionSort.md
touch source/chapter5/09_TheInsertionSort.md
touch source/chapter5/10_TheShellSort.md
touch source/chapter5/11_TheMergeSort.md
touch source/chapter5/12_TheQuickSort.md
touch source/chapter5/13_Summary.md
touch source/chapter5/14_KeyTerms.md
touch source/chapter5/15_DiscussionQuestions.md
touch source/chapter5/16_ProgrammingExercises.md
touch source/chapter6/01_Objectives.md
touch source/chapter6/02_ExamplesofTrees.md
touch source/chapter6/03_VocabularyandDefinitions.md
touch source/chapter6/04_ListofListsRepresentation.md
touch source/chapter6/05_NodesandReferences.md
touch source/chapter6/06_ParseTree.md
touch source/chapter6/07_TreeTraversals.md
touch source/chapter6/08_PriorityQueueswithBinaryHeaps.md
touch source/chapter6/09_BinaryHeapOperations.md
touch source/chapter6/10_BinaryHeapImplementation.md
touch source/chapter6/11_BinarySearchTrees.md
touch source/chapter6/12_SearchTreeOperations.md
touch source/chapter6/13_SearchTreeImplementation.md
touch source/chapter6/14_SearchTreeAnalysis.md
touch source/chapter6/15_BalancedBinarySearchTrees.md
touch source/chapter6/16_AVLTreePerformance.md
touch source/chapter6/17_AVLTreeImplementation.md
touch source/chapter6/18_SummaryofMapADTImplementations.md
touch source/chapter6/19_Summary.md
touch source/chapter6/20_KeyTerms.md
touch source/chapter6/21_DiscussionQuestions.md
touch source/chapter6/22_ProgrammingExercises.md
touch source/chapter7/01_Objectives.md
touch source/chapter7/02_VocabularyandDefinitions.md
touch source/chapter7/03_TheGraphAbstractDataType.md
touch source/chapter7/04_AnAdjacencyMatrix.md
touch source/chapter7/05_AnAdjacencyList.md
touch source/chapter7/06_Implementation.md
touch source/chapter7/07_TheWordLadderProblem.md
touch source/chapter7/08_BuildingtheWordLadderGraph.md
touch source/chapter7/09_ImplementingBreadthFirstSearch.md
touch source/chapter7/10_BreadthFirstSearchAnalysis.md
touch source/chapter7/11_TheKnightsTourProblem.md
touch source/chapter7/12_BuildingtheKnightsTourGraph.md
touch source/chapter7/13_ImplementingKnightsTour.md
touch source/chapter7/14_KnightsTourAnalysis.md
touch source/chapter7/15_GeneralDepthFirstSearch.md
touch source/chapter7/16_DepthFirstSearchAnalysis.md
touch source/chapter7/17_TopologicalSorting.md
touch source/chapter7/18_StronglyConnectedComponents.md
touch source/chapter7/19_ShortestPathProblems.md
touch source/chapter7/20_DijkstrasAlgorithm.md
touch source/chapter7/21_AnalysisofDijkstrasAlgorithm.md
touch source/chapter7/22_PrimsSpanningTreeAlgorithm.md
touch source/chapter7/23_Summary.md
touch source/chapter7/24_KeyTerms.md
touch source/chapter7/25_DiscussionQuestions.md
touch source/chapter7/26_ProgrammingExercises.md
